### ISSUE TITLE
Fam Tree Update 24-25

### ISSUE THREAD

**Issue by WinbertZhang** [UCSBTASA/UCSBTASA.github.io#135]
<img width="1432" alt="Screenshot 2024-11-15 at 3 49 44 PM" src="https://github.com/user-attachments/assets/61c7e868-781a-4ddc-970c-7ffa09a4240c">

- [x] Fam trees should be updated to reflect the new TASA fams
- [x] Ask Winbert/Sam for the info

**Comment by smmzhu** [comment]
Closed in PR #142
